version: '3.6'
services:
  ddnstohome:
    build: ./
    hostname: ddnstohome
    container_name: ddnstohome
    working_dir: /linkease-doc-web
    command: bash
    environment:
      - NODE_ENV=production
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - "../:/linkease-doc-web"
    ports:
      - "0.0.0.0:8088:8080"
    restart: always
